# Generated by Django 5.2.6 on 2025-09-22 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app1", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="myuser",
            name="phone",
            field=models.CharField(
                blank=True, max_length=15, verbose_name="user phone"
            ),
        ),
    ]
